### ISSUE TITLE
Fontes dos dados

### ISSUE THREAD

**Issue by henriquemor** [elhenrico/covid19-Brazil-timeseries#1]
Há notícias que a contabilização dos casos pelo ministério pode estar atrasada. [10 casos não contabilizados em PE, SP e BA no dia 12/03](https://g1.globo.com/bemestar/coronavirus/noticia/2020/03/12/ultimas-noticias-de-coronavirus-de-12-de-marco.ghtml)

Irei manter a contagem seguindo os números oficiais divulgados pelo Ministério da Saúde. [link](http://plataforma.saude.gov.br/novocoronavirus/)

Se alguém tiver outras fontes, podemos discutir aqui.

**Comment by jdflorencio** [comment]
@elhenrico ,
Tenho procurado também fontes oficiais, mas as mesmas não atualizam em tempo hábil. Acredito que se tiver mais pessoas para contribuir de diferentes regiões, baseando se em noticias de portais confiáveis, podemos mantém um fonte de dados atualizada quase que em tempo real.
Posso te dar como exemplo o caso da bahia. como você pode ver nesse site  [](https://g1.globo.com/ba/bahia/noticia/2020/03/17/sobe-para-13-no-de-casos-confirmados-do-coronavirus-na-bahia-diz-secretario-de-saude.ghtml)

https://g1.globo.com/ba/bahia/noticia/2020/03/17/sobe-para-13-no-de-casos-confirmados-do-coronavirus-na-bahia-diz-secretario-de-saude.ghtml

**Comment by henriquemor** [comment]
Percebo que a fonte do Ministério acaba incorporando esses dados uma hora ou outra. Infelizmente, como você disse, os dados ficam com esse hiato de 1 ou 2 dias. 

A impressão é que os números estão muito abaixo da realidade. Talvez pela escolha atual de não testar casos sem gravidade [(fonte)](https://g1.globo.com/bemestar/coronavirus/noticia/2020/03/16/apos-apelo-da-oms-para-testes-em-massa-brasil-mantem-foco-nos-casos-graves-e-diz-estudar-importacao-de-kits-rapidos.ghtml). Vamos acompanhando, @jdflorencio !

**Comment by henriquemor** [comment]
### Decidi por manter os dados nesse repositório refletindo as atualizações oficiais do **Ministério da Saúde**.

Incentivo quem tiver disponibilidade a criar um novo repositório seguindo os dados das secretarias estaduais de saúde para não haver dúvidas sobre as fontes.

Quanto mais informação aberta, melhor.

Manterei aqui aberto para eventuais discussões.

**Comment by fititnt** [comment]
@elhenrico acabei de achar seu projeto por acaso. Os mesmos problemas que você está citando com fonte de dados outras pessoas estão encontrando.

Via @EticaAI nos temos esse repositório aqui https://github.com/EticaAI/coronavirus-cplp porém se por acaso você ou outros que tiverem alguma conta no Facebook, temos umas discussões fechadas neste grupo aqui:

https://www.facebook.com/groups/534884270489894/permalink/535061783805476/

Pessoas que já estão fazendo esse trabalho de documentação e trabalho investigativo são extremamente bem vindas lá!

**Comment by fititnt** [comment]
Outra pessoa que encontrei por acaso e que está fazendo um trabalho de pesquisa que vai alem do que o Ministério da Saúde fornece explicitamente no http://plataforma.saude.gov.br/novocoronavirus/ é o @samsepiol1.

Ele me contactou por facebook, e tem esse repositório aqui focado na região norte https://samsepiol1.github.io/.

Reunir esse pessoal que está pegando dados mais a fundo seria uma ótima ideia.

**Comment by henriquemor** [comment]
@fititnt ótimas referências! 
Coloquei o link para elas neste repositório para dar mais visibilidade aos projetos. 

Seria bem interessante que existissem núcleos de coleta de dados em cada região. Não sei se as atualizações das secretarias estaduais são publicadas na internet ou se os repórteres conseguem na base do telefonema mesmo.

**Comment by fititnt** [comment]
@elhenrico da uma olhada nesse post aqui https://www.facebook.com/groups/534884270489894/permalink/535342560444065/. Lá estamos comparando todos os dashboards, para ver quais são atualizados com mais frequência.

Nesse grupo ali também estão surgindo outros links e referencias. Porém eu cheguei a ouvir falar de quem estava acompanhando a situação na china e, bem no comecinho, antes de ter APIs e tal na china com numero de casos, eles estavam fazendo webscraping bruto (se não me engano de sites de noticias mesmo) pra poder ter os dados mais atuais.

**Comment by endersonmaia** [comment]
olá, existe um esforço voluntário de buscar dados direto nas Secretarias Estaduais de Saúde, focando em **dados por município**, talvez pudéssemos **unir forças**, e resolver essa questão das fontes do MS estarem atrasada e algumas vezes indisponíveis

http://github.com/turicas/covid19-br

* entramos em contato com as secretarias solicitando dados em formatos mais estruturados;
* distribuímos as atividades entre voluntários para buscar os dados e serem checados por uma segunda pessoa;
* existem algumas iniciativas de implementar web scrapers/crawlers para capturar os dados que estejam em PDF ou tabelas não estruturadas;
