### ISSUE TITLE
License

### ISSUE THREAD

**Issue by owahltinez** [elhenrico/covid19-Brazil-timeseries#11]
Hi @elhenrico, thanks again for all the great work! Can you please provide an explicit license for the data in this repo? Preferably, something with as few restrictions as possible...

**Comment by henriquemor** [comment]
Hello @owahltinez!
I've already included a topic about this in the README.md

> Public domain and open-data
> This data can be freely used, re-used and redistributed by anyone. I'll be happy to know what you create with it.

What do you suggest?

**Comment by owahltinez** [comment]
Oh, I missed that! Thanks for clarifying.

I can't advise you on how to license your work. From my point of view as a data user, I like the way it currently is because it's unambiguous and easy to work with.

**Comment by henriquemor** [comment]
Great! But I'm always open to any suggestions as I'm new to this :)
I've been working on this so everyone could have a more hassle free access to the data and build helpful projects like yours!
