### ISSUE TITLE
Outlier in data 20th August

### ISSUE THREAD

**Issue by martinbenes1996** [elhenrico/covid19-Brazil-timeseries#18]
20th August seems to be wrong. The data in a single day are absolutely out of overall trend before and after.

Is it possible to validate the data with the original source? Thank you.

**Comment by henriquemor** [comment]
Hello, @martinbenes1996,
Thanks for pointing this problem! 
I fixed the data with this last commit:  https://github.com/elhenrico/covid19-Brazil-timeseries/commit/ba70fa75754074358d34d7b992bfc83f28b692ba
I'll close the issue but feel free to reach out in any case
Best regards
