### ISSUE TITLE
Stability of CSV files

### ISSUE THREAD

**Issue by owahltinez** [elhenrico/covid19-Brazil-timeseries#4]
Hi @elhenrico, first of all thanks so much for this -- awesome work! I am now using your CSV files to add region-level data to my [Open COVID-19](https://github.com/open-covid-19/data) project.

I am currently pulling the CSV files from the GitHub Raw cache ([like this one](https://raw.githubusercontent.com/elhenrico/covid19-Brazil-timeseries/master/confirmed-cases.csv)) and I wanted to understand how stable these files are, whether you are likely to change the name, location, format, etc. In case of any changes, how can I be notified so I can update my scripts appropriately?

**Comment by henriquemor** [comment]
You did an amazing job on your project!

I am keeping the name and structure of the files constant precisely for this case. Would changing something or adding an additional column help you?

Usually I update the data daily according to the last daily update from our Ministry.

I will let you know on any possible breaking changes.

**Comment by owahltinez** [comment]
Thanks for the kind words :)

The format of the files looks very clean to me, I wouldn't suggest changing it. Adding more columns would be a breaking change for my scripts, since I'm assuming columns are dates except for the first two.

Are you updating the data manually, or are you using some form of automation?

**Comment by henriquemor** [comment]
Manually with the help of some tools to make it faster.

As the government has shown itself inconsistent in the disclosure of the data, often changing it or going offline without notice, I found the manual approach better for now.

There are others automating it, but last week many were lacking days of data due to this instability.

**Comment by henriquemor** [comment]
@owahltinez As you asked me to contact you regarding breaking changes, I decided to **change the date format**
from 23/2 to 23/02/2021
Happy new year

**Comment by owahltinez** [comment]
Thank you for the heads up @elhenrico!
