### ISSUE TITLE
Integração de conjunto de dados latino-americana

### ISSUE THREAD

**Issue by pablodz** [elhenrico/covid19-Brazil-timeseries#5]
Olá, juntamente com uma organização sem fins lucrativos, estamos tentando centralizar as informações de infectados / mortos / recuperados covid-19 e estamos procurando uma pessoa encarregada de cada país. No seu caso, Brazil.

O formato csv está sendo tratado de acordo com o formato global https://github.com/CSSEGISandData/COVID-19 para poder coletar os dados.
Isso inclui as seguintes colunas:
![image](https://user-images.githubusercontent.com/28235457/77353780-9df15f80-6d0f-11ea-8b7b-12e53b3b33df.png)

Para a Brazil, é necessária atualização diária para esses lugares:

![image](https://user-images.githubusercontent.com/28235457/77353762-95992480-6d0f-11ea-91dc-381c4626b30f.png)

Você poderia me dizer se está interessado em contribuir, por favor.
O conjunto de dados centralizado é proposto neste repositório:
https://github.com/DataScienceResearchPeru/covid-19_latinoamerica

**Comment by henriquemor** [comment]
Olá @ZurMaD ! Parabéns pela sua iniciativa!

Pelo que entendi será necessário não só o update diário como a atualização dos dados que estão faltando nos arquivos já existentes, correto?

Infelizmente não tenho no momento disponibilidade para cuidar deste input de dados. Mas fique à vontade para usar qualquer dado disponibilizado por aqui! Os dados apresentados são exatamente os divulgados pelo [Ministério da Saúde](https://covid.saude.gov.br/), sem alterações.

Agradeço a mensagem! Irei colocar um link para seu repositório e deixarei esta issue aberta para dar mais visibilidade ao seu projeto!
Abraços (seu português é ótimo)

**Comment by pablodz** [comment]
Muito obrigado pela resposta, em qualquer caso, criaremos um programa para atualizar automaticamente, levando seu repositório como fonte. Se você alterar os arquivos, informe-nos.
Thanks for all @elhenrico !

**Comment by henriquemor** [comment]
Toda a estrutura e nomenclatura de arquivos deverá permanecer como está.

Se, por algum acaso algo mudar, te avisarei!
